### ISSUE TITLE
Is there any way to define boundary conditions?

### ISSUE THREAD

**Issue by laughingrice** [ChevronETC/Devito.jl#51]
The most basic convection equation example for devito implements boundary conditions by defining the explicitly, i.e

```python
x, y = grid.dimensions
t = grid.stepping_dim
bc_left = Eq(u[t + 1, 0, y], 1.)
```

I cannot find any similar way to achieve this in devito

It seems that t and x can be either
```julia
t = u.o.time_dim
x, y = u.o.space_dimensions
```
or

```julia
x, y, t = dimensions(u)
```

or a few other options. But I cannot find anything that would match

```julia
bc_left = Eq(u[t + 1, 0, y], 1.)
```

`u.o[1,1]` seems to be defined,  but `u.o[t,1]` isn't

**Comment by laughingrice** [comment]
Not super intuitive and I'm not sure wha the example is doing in terms of boundary conditions, but this works

```julia
x, t = dimensions(u)
bc = Eq(u.o.__getitem__((t+1,0)), 0.)
```

**Comment by samtkaplan** [comment]
@laughingrice Can you provide a link to the Python Devito convection equation example?  Devito.jl is certainly incomplete.  So far, the focus has being on the wave equation.  But, adding examples like this can definitely help fill in some of the gaps.  Thanks for bringing up the topic!

**Comment by laughingrice** [comment]
@samtkaplan  I've started working through the examples here:

https://github.com/devitocodes/devito/tree/master/examples/cfd

I will try and make a proper translation of the example(s) and maybe update Devito.jl to make implementation cleaner and easier.

**Comment by deckerla** [comment]
@laughingrice very interesting discussion!  

I am excited to see your implementation of that example, if you feel comfortable could you make a PR with it for it to be added to the `Devito.jl` documentation when you are done?  Having these sort of examples would be extremely useful for new users and help us identify these kinds of missing features.

As you have noticed, we don't currently support `stepping_dim(grid)`.  However, as you have also seen, that stepping dim can be accessed from a devito time function.

Something to be aware of is that with the Devito.jl functions the dimension order is fast -> slow, keeping with the Julia convention.  In devito.py dimension ordering is slow -> fast.  I'm not sure how accessing PyCall objects with .o changes things though!

**Comment by deckerla** [comment]
@laughingrice I think the functionality you want has been added in the last PR. Please let us know if you are looking for something else or have other questions!

**Comment by laughingrice** [comment]
@deckerla I'll have a look at the exact changes in the last PR, in the meantime I made a Julia implementation for the first example in the CFD example set (2D convection with Dirichlet boundary conditions) and created a PR for it.

Data is in column major order and shows axes correctly in the plotting functions.
Text should (at least mostly) match the Julia implementation.

Quite a few things had to go through the PyCall interface (u.o and grid.o), although it does help keep the global namespace less cluttered. So there is an advantage to taking that route. I might also lean towards making dx,dy,dz,dt fields of TimeFunction instead of independent functions, as those are pretty common variable names.

Will try to find time soon to progress to the next examples.

**Comment by laughingrice** [comment]
@deckerla Had a look, it allows bypassing a direct call to PyObject, replacing

```julia
t, x, y = u.o.dimensions
```
with

```julia
t = stepping_dim(grid)
y, x = dimensions(grid)
```

Still missing a nice version for

```julia
"bc_left = Eq(u.o.__getitem__((t + 1, 0, y)), 1.);
"bc_right = Eq(u.o.__getitem__((t + 1, nx-1, y)), 1.);
"bc_top = Eq(u.o.__getitem__((t + 1, x, ny-1)), 1.);
"bc_bottom = Eq(u.o.__getitem__((t + 1, x, 0)), 1.);
```

This can be achieved using this

```julia
import Base.getindex

function getindex(func::TimeFunction, ind...)
    return func.o.__getitem__(ind)
end;

bc_left = Eq(u[t + 1, 0, y], 1.);
bc_right = Eq(u[t + 1, nx-1, y], 1.);
bc_top = Eq(u[t + 1, x, ny-1], 1.);
bc_bottom = Eq(u[t + 1, x, 0], 1.);
```

Need to see where to add that getindex function definition.
Also, ideally should be a separate pull request to isolate examples from code changes, but they are co-dependent, so may need to happen in order

**Comment by deckerla** [comment]
@laughingrice I believe that `getindex (func::Union{TimeFunction,Function}, args...)` is currently supported.
It appears in the source here:

https://github.com/ChevronETC/Devito.jl/blob/d08100a0c726564795d03c39a387517e9b9a629b/src/Devito.jl#L1117

Please let us know if it's not working for you!

Also, you may need to do something like:
`bc_left = Eq(u[ y, 0, t + spacing(t)], 1.);`

**Comment by laughingrice** [comment]
@deckerla Ahh, missed that. I was using non-reversed indices which that threw an error I misinterpreted. Updated and cleaned up the covection example to account for all of these. Only thing missing now is to expose the Devito.devito.solve function
