### ISSUE TITLE
sparse time function coordinates

### ISSUE THREAD

**Issue by deckerla** [ChevronETC/Devito.jl#79]
providing a sparse time function with coordinates at construction seems to produce different results than writing them later

**Comment by deckerla** [comment]
This issue is actually indicative of something bigger -- arguments passed to `SparseTimeFunction` during construction are sent without transformation to pythonic ordering.  We should transform the arguments like is done with the creation of `Grid` objects

**Comment by samtkaplan** [comment]
@deckerla In addition, it looks like the `coordinates` [method](https://github.com/ChevronETC/Devito.jl/blob/d606e4e9a640c9792cfff8f34ee17a52d55e5ac5/src/Devito.jl#L1142-L1145) for dense MPI arrays does not `reverse` the first dimension.  This is inconsistent with the corresponding non-MPI [method](https://github.com/ChevronETC/Devito.jl/blob/d606e4e9a640c9792cfff8f34ee17a52d55e5ac5/src/Devito.jl#L1136-L1139) that does, indeed, `reverse` the first dimension.

**Comment by samtkaplan** [comment]
@deckerla In light of #88 and #89, I guess this can be closed?

**Comment by deckerla** [comment]
Yes, I agree
