### ISSUE TITLE
serial use of `convert` results in initialization of MPI

### ISSUE THREAD

**Issue by jkwashbourne** [ChevronETC/Devito.jl#81]
I would like to be able to use `convert` without initializing MPI. 

https://github.com/ChevronETC/Devito.jl/blob/5fabbf1951c1bb6338491c5d7dc1607033ffcc19/src/Devito.jl#L138

indicates that `MPI.Init()` is always called. 

is it worth considering being able to use `convert` for a serial job without init? motivation: I would like to be able to run the same operator serial/MPI.

**Comment by jkwashbourne** [comment]
Alternative: rely on `DEVITO_MPI` environment variable

`has_MPI = get(ENV, "DEVITO_MPI", "0") == "1"`

**Comment by samtkaplan** [comment]
So, that line of code will only call `MPI.Init()` if `MPI.Initialized()` returns false.  In other words, it only initializes MPI if MPI is not already initialized. Second, that method will only be called when using MPI.  In other words, if you are not using MPI, then the library will not make a type of `DevitoMPIArray` and, hence, the method will not get dispatched to.  So, making any changes here will not be related to your motivation, I think.

With respect to that line of code (and similar scattered throughout the code), I would not be against removing them, and relying on the user to call MPI.Init() once at the start of their code.

**Comment by samtkaplan** [comment]
closing due to the closure of #86.
